application_soap:
    resource: "@ApplicationSoapBundle/Controller/"
    type:     annotation
    prefix:   /

ws_soap:
    path: /soap/{service}
    defaults: { _controller: ApplicationSoapBundle:WebServiceProvider:getWebService }
