<?php

namespace Proxies\__CG__\Application\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FrmFormItemPool extends \Application\CoreBundle\Entity\FrmFormItemPool implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'id', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'valorPadre', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'orden', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'idSeccionPool', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'idFormItem', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'idPadre', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'validacionPadre');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'id', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'valorPadre', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'orden', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'idSeccionPool', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'idFormItem', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'idPadre', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItemPool' . "\0" . 'validacionPadre');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FrmFormItemPool $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorPadre($valorPadre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorPadre', array($valorPadre));

        return parent::setValorPadre($valorPadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorPadre', array());

        return parent::getValorPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', array($orden));

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', array());

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSeccionPool(\Application\CoreBundle\Entity\FrmSeccionPool $idSeccionPool = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSeccionPool', array($idSeccionPool));

        return parent::setIdSeccionPool($idSeccionPool);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSeccionPool()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSeccionPool', array());

        return parent::getIdSeccionPool();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdFormItem(\Application\CoreBundle\Entity\FrmFormItem $idFormItem = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdFormItem', array($idFormItem));

        return parent::setIdFormItem($idFormItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdFormItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFormItem', array());

        return parent::getIdFormItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPadre(\Application\CoreBundle\Entity\FrmFormItemPool $idPadre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPadre', array($idPadre));

        return parent::setIdPadre($idPadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPadre', array());

        return parent::getIdPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidacionPadre(\Application\CoreBundle\Entity\CtlValidacionCampo $validacionPadre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidacionPadre', array($validacionPadre));

        return parent::setValidacionPadre($validacionPadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidacionPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidacionPadre', array());

        return parent::getValidacionPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
