<?php

namespace Proxies\__CG__\Minsal\CitasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CitDistribucion extends \Minsal\CitasBundle\Entity\CitDistribucion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'id', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'primera', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'subsecuente', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'mes', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'yrs', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'dia', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'fechahoramod', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'maxCitasAgregadas', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idEstadoDistribucion', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idAtenAreaModEstab', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idConsultorio', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idusuariomod', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idAreaModEstab', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idEmpleado', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idRangohora', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idTipoDistribucion');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'id', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'primera', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'subsecuente', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'mes', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'yrs', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'dia', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'fechahoramod', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'maxCitasAgregadas', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idEstadoDistribucion', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idAtenAreaModEstab', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idConsultorio', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idusuariomod', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idAreaModEstab', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idEmpleado', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idRangohora', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitDistribucion' . "\0" . 'idTipoDistribucion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CitDistribucion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimera($primera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimera', array($primera));

        return parent::setPrimera($primera);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimera', array());

        return parent::getPrimera();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubsecuente($subsecuente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubsecuente', array($subsecuente));

        return parent::setSubsecuente($subsecuente);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubsecuente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubsecuente', array());

        return parent::getSubsecuente();
    }

    /**
     * {@inheritDoc}
     */
    public function setMes($mes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMes', array($mes));

        return parent::setMes($mes);
    }

    /**
     * {@inheritDoc}
     */
    public function getMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMes', array());

        return parent::getMes();
    }

    /**
     * {@inheritDoc}
     */
    public function setYrs($yrs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYrs', array($yrs));

        return parent::setYrs($yrs);
    }

    /**
     * {@inheritDoc}
     */
    public function getYrs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYrs', array());

        return parent::getYrs();
    }

    /**
     * {@inheritDoc}
     */
    public function setDia($dia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDia', array($dia));

        return parent::setDia($dia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDia', array());

        return parent::getDia();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahorareg($fechahorareg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahorareg', array($fechahorareg));

        return parent::setFechahorareg($fechahorareg);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahorareg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahorareg', array());

        return parent::getFechahorareg();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahoramod($fechahoramod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahoramod', array($fechahoramod));

        return parent::setFechahoramod($fechahoramod);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahoramod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahoramod', array());

        return parent::getFechahoramod();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxCitasAgregadas($maxCitasAgregadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxCitasAgregadas', array($maxCitasAgregadas));

        return parent::setMaxCitasAgregadas($maxCitasAgregadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxCitasAgregadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxCitasAgregadas', array());

        return parent::getMaxCitasAgregadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstadoDistribucion(\Minsal\CitasBundle\Entity\CitEstadoDistribucion $idEstadoDistribucion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstadoDistribucion', array($idEstadoDistribucion));

        return parent::setIdEstadoDistribucion($idEstadoDistribucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstadoDistribucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstadoDistribucion', array());

        return parent::getIdEstadoDistribucion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAtenAreaModEstab(\Minsal\SiapsBundle\Entity\MntAtenAreaModEstab $idAtenAreaModEstab = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAtenAreaModEstab', array($idAtenAreaModEstab));

        return parent::setIdAtenAreaModEstab($idAtenAreaModEstab);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAtenAreaModEstab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAtenAreaModEstab', array());

        return parent::getIdAtenAreaModEstab();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdConsultorio(\Minsal\SiapsBundle\Entity\MntConsultorio $idConsultorio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdConsultorio', array($idConsultorio));

        return parent::setIdConsultorio($idConsultorio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdConsultorio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdConsultorio', array());

        return parent::getIdConsultorio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuarioreg(\Application\Sonata\UserBundle\Entity\User $idusuarioreg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuarioreg', array($idusuarioreg));

        return parent::setIdusuarioreg($idusuarioreg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuarioreg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuarioreg', array());

        return parent::getIdusuarioreg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuariomod(\Application\Sonata\UserBundle\Entity\User $idusuariomod = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuariomod', array($idusuariomod));

        return parent::setIdusuariomod($idusuariomod);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuariomod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuariomod', array());

        return parent::getIdusuariomod();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAreaModEstab(\Minsal\SiapsBundle\Entity\MntAreaModEstab $idAreaModEstab = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAreaModEstab', array($idAreaModEstab));

        return parent::setIdAreaModEstab($idAreaModEstab);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAreaModEstab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAreaModEstab', array());

        return parent::getIdAreaModEstab();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmpleado(\Minsal\SiapsBundle\Entity\MntEmpleado $idEmpleado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmpleado', array($idEmpleado));

        return parent::setIdEmpleado($idEmpleado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmpleado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmpleado', array());

        return parent::getIdEmpleado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRangohora(\Minsal\SiapsBundle\Entity\MntRangohora $idRangohora = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRangohora', array($idRangohora));

        return parent::setIdRangohora($idRangohora);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRangohora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRangohora', array());

        return parent::getIdRangohora();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipoDistribucion(\Minsal\CitasBundle\Entity\CitTipoDistribucion $idTipoDistribucion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipoDistribucion', array($idTipoDistribucion));

        return parent::setIdTipoDistribucion($idTipoDistribucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipoDistribucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipoDistribucion', array());

        return parent::getIdTipoDistribucion();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getDiaSemana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiaSemana', array());

        return parent::getDiaSemana();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreMes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreMes', array());

        return parent::getNombreMes();
    }

}
