<?php

namespace Proxies\__CG__\Minsal\SiapsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MntExpediente extends \Minsal\SiapsBundle\Entity\MntExpediente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'numero', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'habilitado', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'fechaCreacion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'horaCreacion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'numeroTemporal', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'expedienteFisicoEliminado', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'cun', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'idCreacionExpediente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'idPaciente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'detalleJustificacion');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'numero', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'habilitado', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'fechaCreacion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'horaCreacion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'numeroTemporal', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'expedienteFisicoEliminado', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'cun', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'idCreacionExpediente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'idPaciente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntExpediente' . "\0" . 'detalleJustificacion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MntExpediente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setHabilitado($habilitado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHabilitado', array($habilitado));

        return parent::setHabilitado($habilitado);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabilitado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabilitado', array());

        return parent::getHabilitado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraCreacion($horaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraCreacion', array($horaCreacion));

        return parent::setHoraCreacion($horaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraCreacion', array());

        return parent::getHoraCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroTemporal($numeroTemporal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroTemporal', array($numeroTemporal));

        return parent::setNumeroTemporal($numeroTemporal);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTemporal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTemporal', array());

        return parent::getNumeroTemporal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCreacionExpediente(\Minsal\SiapsBundle\Entity\CtlCreacionExpediente $idCreacionExpediente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCreacionExpediente', array($idCreacionExpediente));

        return parent::setIdCreacionExpediente($idCreacionExpediente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCreacionExpediente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCreacionExpediente', array());

        return parent::getIdCreacionExpediente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimiento(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimiento', array($idEstablecimiento));

        return parent::setIdEstablecimiento($idEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimiento', array());

        return parent::getIdEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPaciente(\Minsal\SiapsBundle\Entity\MntPaciente $idPaciente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPaciente', array($idPaciente));

        return parent::setIdPaciente($idPaciente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPaciente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPaciente', array());

        return parent::getIdPaciente();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpedienteFisicoEliminado($expedienteFisicoEliminado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpedienteFisicoEliminado', array($expedienteFisicoEliminado));

        return parent::setExpedienteFisicoEliminado($expedienteFisicoEliminado);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpedienteFisicoEliminado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpedienteFisicoEliminado', array());

        return parent::getExpedienteFisicoEliminado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCun($cun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCun', array($cun));

        return parent::setCun($cun);
    }

    /**
     * {@inheritDoc}
     */
    public function getCun()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCun', array());

        return parent::getCun();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetalleJustificacion(\Minsal\SiapsBundle\Entity\MntJustificacionCumNoValido $detalleJustificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetalleJustificacion', array($detalleJustificacion));

        return parent::addDetalleJustificacion($detalleJustificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetalleJustificacion(\Minsal\SiapsBundle\Entity\MntJustificacionCumNoValido $detalleJustificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetalleJustificacion', array($detalleJustificacion));

        return parent::removeDetalleJustificacion($detalleJustificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalleJustificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalleJustificacion', array());

        return parent::getDetalleJustificacion();
    }

}
