<?php

namespace Proxies\__CG__\Minsal\SiapsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MntAreaModEstab extends \Minsal\SiapsBundle\Entity\MntAreaModEstab implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'idAreaAtencion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'idModalidadEstab', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'atenciones', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'idServicioExternoEstab');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'idAreaAtencion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'idModalidadEstab', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'atenciones', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAreaModEstab' . "\0" . 'idServicioExternoEstab');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MntAreaModEstab $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAreaAtencion(\Minsal\SiapsBundle\Entity\CtlAreaAtencion $idAreaAtencion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAreaAtencion', array($idAreaAtencion));

        return parent::setIdAreaAtencion($idAreaAtencion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAreaAtencion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAreaAtencion', array());

        return parent::getIdAreaAtencion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimiento(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimiento', array($idEstablecimiento));

        return parent::setIdEstablecimiento($idEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimiento', array());

        return parent::getIdEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdModalidadEstab(\Minsal\SiapsBundle\Entity\MntModalidadEstablecimiento $idModalidadEstab = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdModalidadEstab', array($idModalidadEstab));

        return parent::setIdModalidadEstab($idModalidadEstab);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdModalidadEstab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdModalidadEstab', array());

        return parent::getIdModalidadEstab();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreAreaModEstab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreAreaModEstab', array());

        return parent::getNombreAreaModEstab();
    }

    /**
     * {@inheritDoc}
     */
    public function addAtencione(\Minsal\SiapsBundle\Entity\CtlAtencion $atenciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAtencione', array($atenciones));

        return parent::addAtencione($atenciones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAtencione(\Minsal\SiapsBundle\Entity\CtlAtencion $atenciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAtencione', array($atenciones));

        return parent::removeAtencione($atenciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtenciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtenciones', array());

        return parent::getAtenciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdServicioExternoEstab(\Minsal\SiapsBundle\Entity\MntServicioExternoEstablecimiento $idServicioExternoEstab = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdServicioExternoEstab', array($idServicioExternoEstab));

        return parent::setIdServicioExternoEstab($idServicioExternoEstab);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdServicioExternoEstab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdServicioExternoEstab', array());

        return parent::getIdServicioExternoEstab();
    }

}
