<?php

namespace Proxies\__CG__\Minsal\SiapsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MntModalidadEstablecimiento extends \Minsal\SiapsBundle\Entity\MntModalidadEstablecimiento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'tieneFarmacia', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'repetitiva', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'poseeBodega', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'idModalidad');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'tieneFarmacia', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'repetitiva', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'poseeBodega', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntModalidadEstablecimiento' . "\0" . 'idModalidad');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MntModalidadEstablecimiento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTieneFarmacia($tieneFarmacia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTieneFarmacia', array($tieneFarmacia));

        return parent::setTieneFarmacia($tieneFarmacia);
    }

    /**
     * {@inheritDoc}
     */
    public function getTieneFarmacia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTieneFarmacia', array());

        return parent::getTieneFarmacia();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepetitiva($repetitiva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepetitiva', array($repetitiva));

        return parent::setRepetitiva($repetitiva);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepetitiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepetitiva', array());

        return parent::getRepetitiva();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimiento(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimiento', array($idEstablecimiento));

        return parent::setIdEstablecimiento($idEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimiento', array());

        return parent::getIdEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdModalidad(\Minsal\SiapsBundle\Entity\CtlModalidad $idModalidad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdModalidad', array($idModalidad));

        return parent::setIdModalidad($idModalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdModalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdModalidad', array());

        return parent::getIdModalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoseeBodega($poseeBodega)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoseeBodega', array($poseeBodega));

        return parent::setPoseeBodega($poseeBodega);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoseeBodega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoseeBodega', array());

        return parent::getPoseeBodega();
    }

}
