<?php

namespace Proxies\__CG__\Minsal\SiapsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CtlEstablecimiento extends \Minsal\SiapsBundle\Entity\CtlEstablecimiento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'nombre', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'direccion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'telefono', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'fax', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'latitud', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'longitud', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'idNivelMinsal', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'codUcsf', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'activo', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'tipoExpediente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'configurado', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'citasSinExpediente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'diasIntermediosCitas', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'idEstablecimientoPadre', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'idMunicipio', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'idTipoEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'serviciosExternos');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'nombre', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'direccion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'telefono', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'fax', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'latitud', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'longitud', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'idNivelMinsal', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'codUcsf', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'activo', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'tipoExpediente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'configurado', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'citasSinExpediente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'diasIntermediosCitas', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'idEstablecimientoPadre', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'idMunicipio', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'idTipoEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\CtlEstablecimiento' . "\0" . 'serviciosExternos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CtlEstablecimiento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitud($latitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitud', array($latitud));

        return parent::setLatitud($latitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitud', array());

        return parent::getLatitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitud($longitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitud', array($longitud));

        return parent::setLongitud($longitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitud', array());

        return parent::getLongitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdNivelMinsal($idNivelMinsal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdNivelMinsal', array($idNivelMinsal));

        return parent::setIdNivelMinsal($idNivelMinsal);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdNivelMinsal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNivelMinsal', array());

        return parent::getIdNivelMinsal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodUcsf($codUcsf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodUcsf', array($codUcsf));

        return parent::setCodUcsf($codUcsf);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodUcsf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodUcsf', array());

        return parent::getCodUcsf();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoExpediente($tipoExpediente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoExpediente', array($tipoExpediente));

        return parent::setTipoExpediente($tipoExpediente);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoExpediente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoExpediente', array());

        return parent::getTipoExpediente();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfigurado($configurado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfigurado', array($configurado));

        return parent::setConfigurado($configurado);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfigurado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfigurado', array());

        return parent::getConfigurado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMunicipio(\Minsal\SiapsBundle\Entity\CtlMunicipio $idMunicipio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMunicipio', array($idMunicipio));

        return parent::setIdMunicipio($idMunicipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMunicipio', array());

        return parent::getIdMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipoEstablecimiento(\Minsal\SiapsBundle\Entity\CtlTipoEstablecimiento $idTipoEstablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipoEstablecimiento', array($idTipoEstablecimiento));

        return parent::setIdTipoEstablecimiento($idTipoEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipoEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipoEstablecimiento', array());

        return parent::getIdTipoEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoFarmacia($tipoFarmacia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoFarmacia', array($tipoFarmacia));

        return parent::setTipoFarmacia($tipoFarmacia);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoFarmacia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoFarmacia', array());

        return parent::getTipoFarmacia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimientoPadre(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimientoPadre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimientoPadre', array($idEstablecimientoPadre));

        return parent::setIdEstablecimientoPadre($idEstablecimientoPadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimientoPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimientoPadre', array());

        return parent::getIdEstablecimientoPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCitasSinExpediente($citasSinExpediente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCitasSinExpediente', array($citasSinExpediente));

        return parent::setCitasSinExpediente($citasSinExpediente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCitasSinExpediente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCitasSinExpediente', array());

        return parent::getCitasSinExpediente();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiasIntermediosCitas($diasIntermediosCitas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiasIntermediosCitas', array($diasIntermediosCitas));

        return parent::setDiasIntermediosCitas($diasIntermediosCitas);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiasIntermediosCitas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiasIntermediosCitas', array());

        return parent::getDiasIntermediosCitas();
    }

    /**
     * {@inheritDoc}
     */
    public function addServiciosExterno(\Minsal\SiapsBundle\Entity\MntServicioExterno $serviciosExternos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addServiciosExterno', array($serviciosExternos));

        return parent::addServiciosExterno($serviciosExternos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeServiciosExterno(\Minsal\SiapsBundle\Entity\MntServicioExterno $serviciosExternos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeServiciosExterno', array($serviciosExternos));

        return parent::removeServiciosExterno($serviciosExternos);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiciosExternos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiciosExternos', array());

        return parent::getServiciosExternos();
    }

}
