<?php

namespace Proxies\__CG__\Minsal\CitasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CitCitasDia extends \Minsal\CitasBundle\Entity\CitCitasDia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'id', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'fecha', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'ipcita', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'ipconfirmado', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'citaPor', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'orden', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'numeroExpedienteReferencia', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idEstado', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idJustificacion', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idTipocita', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idEstablecimientoReferencia', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idAreaModEstab', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idAtenAreaModEstab', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idEmpleado', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idExpediente', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idRangohora', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idPrioridad', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idusuariomod', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'fechahoramod', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idDistribucion');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'id', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'fecha', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'ipcita', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'ipconfirmado', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'citaPor', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'orden', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'numeroExpedienteReferencia', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idEstado', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idJustificacion', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idTipocita', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idEstablecimientoReferencia', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idAreaModEstab', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idAtenAreaModEstab', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idEmpleado', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idExpediente', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idRangohora', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idPrioridad', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idusuariomod', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'fechahoramod', '' . "\0" . 'Minsal\\CitasBundle\\Entity\\CitCitasDia' . "\0" . 'idDistribucion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CitCitasDia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahorareg($fechahorareg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahorareg', array($fechahorareg));

        return parent::setFechahorareg($fechahorareg);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahorareg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahorareg', array());

        return parent::getFechahorareg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpcita($ipcita)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpcita', array($ipcita));

        return parent::setIpcita($ipcita);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpcita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpcita', array());

        return parent::getIpcita();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpconfirmado($ipconfirmado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpconfirmado', array($ipconfirmado));

        return parent::setIpconfirmado($ipconfirmado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpconfirmado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpconfirmado', array());

        return parent::getIpconfirmado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCitaPor($citaPor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCitaPor', array($citaPor));

        return parent::setCitaPor($citaPor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCitaPor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCitaPor', array());

        return parent::getCitaPor();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', array($orden));

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', array());

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstado(\Minsal\CitasBundle\Entity\CitEstadoCita $idEstado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstado', array($idEstado));

        return parent::setIdEstado($idEstado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstado', array());

        return parent::getIdEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdJustificacion(\Minsal\CitasBundle\Entity\CitJustificacion $idJustificacion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdJustificacion', array($idJustificacion));

        return parent::setIdJustificacion($idJustificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdJustificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdJustificacion', array());

        return parent::getIdJustificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipocita(\Minsal\CitasBundle\Entity\CitTipocita $idTipocita = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipocita', array($idTipocita));

        return parent::setIdTipocita($idTipocita);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipocita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipocita', array());

        return parent::getIdTipocita();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimiento(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimiento', array($idEstablecimiento));

        return parent::setIdEstablecimiento($idEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimiento', array());

        return parent::getIdEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimientoReferencia(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimientoReferencia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimientoReferencia', array($idEstablecimientoReferencia));

        return parent::setIdEstablecimientoReferencia($idEstablecimientoReferencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimientoReferencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimientoReferencia', array());

        return parent::getIdEstablecimientoReferencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuarioreg(\Application\Sonata\UserBundle\Entity\User $idusuarioreg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuarioreg', array($idusuarioreg));

        return parent::setIdusuarioreg($idusuarioreg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuarioreg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuarioreg', array());

        return parent::getIdusuarioreg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAreaModEstab(\Minsal\SiapsBundle\Entity\MntAreaModEstab $idAreaModEstab = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAreaModEstab', array($idAreaModEstab));

        return parent::setIdAreaModEstab($idAreaModEstab);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAreaModEstab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAreaModEstab', array());

        return parent::getIdAreaModEstab();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAtenAreaModEstab(\Minsal\SiapsBundle\Entity\MntAtenAreaModEstab $idAtenAreaModEstab = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAtenAreaModEstab', array($idAtenAreaModEstab));

        return parent::setIdAtenAreaModEstab($idAtenAreaModEstab);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAtenAreaModEstab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAtenAreaModEstab', array());

        return parent::getIdAtenAreaModEstab();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmpleado(\Minsal\SiapsBundle\Entity\MntEmpleado $idEmpleado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmpleado', array($idEmpleado));

        return parent::setIdEmpleado($idEmpleado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmpleado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmpleado', array());

        return parent::getIdEmpleado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdExpediente(\Minsal\SiapsBundle\Entity\MntExpediente $idExpediente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdExpediente', array($idExpediente));

        return parent::setIdExpediente($idExpediente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdExpediente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdExpediente', array());

        return parent::getIdExpediente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRangohora(\Minsal\SiapsBundle\Entity\MntRangohora $idRangohora = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRangohora', array($idRangohora));

        return parent::setIdRangohora($idRangohora);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRangohora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRangohora', array());

        return parent::getIdRangohora();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPrioridad(\Minsal\CitasBundle\Entity\CtlPrioridad $idPrioridad = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPrioridad', array($idPrioridad));

        return parent::setIdPrioridad($idPrioridad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPrioridad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPrioridad', array());

        return parent::getIdPrioridad();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuariomod(\Application\Sonata\UserBundle\Entity\User $idusuariomod = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuariomod', array($idusuariomod));

        return parent::setIdusuariomod($idusuariomod);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuariomod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuariomod', array());

        return parent::getIdusuariomod();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahoramod($fechahoramod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahoramod', array($fechahoramod));

        return parent::setFechahoramod($fechahoramod);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahoramod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahoramod', array());

        return parent::getFechahoramod();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDistribucion(\Minsal\CitasBundle\Entity\CitDistribucion $idDistribucion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDistribucion', array($idDistribucion));

        return parent::setIdDistribucion($idDistribucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDistribucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDistribucion', array());

        return parent::getIdDistribucion();
    }

    /**
     * {@inheritDoc}
     */
    public function createQueryBuilder($alias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createQueryBuilder', array($alias));

        return parent::createQueryBuilder($alias);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroExpedienteReferencia($numeroExpedienteReferencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroExpedienteReferencia', array($numeroExpedienteReferencia));

        return parent::setNumeroExpedienteReferencia($numeroExpedienteReferencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroExpedienteReferencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroExpedienteReferencia', array());

        return parent::getNumeroExpedienteReferencia();
    }

}
