<?php

namespace Proxies\__CG__\Application\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CtlCampo extends \Application\CoreBundle\Entity\CtlCampo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'id', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'nombre', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'tamano', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'esNulo', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'idTipoCampo', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'idTabla');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'id', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'nombre', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'tamano', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'esNulo', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'idTipoCampo', '' . "\0" . 'Application\\CoreBundle\\Entity\\CtlCampo' . "\0" . 'idTabla');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CtlCampo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTamano($tamano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTamano', array($tamano));

        return parent::setTamano($tamano);
    }

    /**
     * {@inheritDoc}
     */
    public function getTamano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTamano', array());

        return parent::getTamano();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsNulo($esNulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsNulo', array($esNulo));

        return parent::setEsNulo($esNulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsNulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsNulo', array());

        return parent::getEsNulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipoCampo(\Application\CoreBundle\Entity\CtlTipoCampo $idTipoCampo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipoCampo', array($idTipoCampo));

        return parent::setIdTipoCampo($idTipoCampo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipoCampo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipoCampo', array());

        return parent::getIdTipoCampo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTabla(\Application\CoreBundle\Entity\CtlTabla $idTabla = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTabla', array($idTabla));

        return parent::setIdTabla($idTabla);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTabla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTabla', array());

        return parent::getIdTabla();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreExtend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreExtend', array());

        return parent::getNombreExtend();
    }

}
