<?php

namespace Proxies\__CG__\Minsal\SiapsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MntConsultorio extends \Minsal\SiapsBundle\Entity\MntConsultorio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'descripcion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'fechahoramod', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'nombre', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'idusuariomod', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'idAreaModEstab');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'descripcion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'fechahoramod', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'nombre', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'idusuariomod', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntConsultorio' . "\0" . 'idAreaModEstab');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MntConsultorio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahorareg($fechahorareg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahorareg', array($fechahorareg));

        return parent::setFechahorareg($fechahorareg);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahorareg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahorareg', array());

        return parent::getFechahorareg();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahoramod($fechahoramod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahoramod', array($fechahoramod));

        return parent::setFechahoramod($fechahoramod);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahoramod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahoramod', array());

        return parent::getFechahoramod();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuarioreg(\Application\Sonata\UserBundle\Entity\User $idusuarioreg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuarioreg', array($idusuarioreg));

        return parent::setIdusuarioreg($idusuarioreg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuarioreg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuarioreg', array());

        return parent::getIdusuarioreg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuariomod(\Application\Sonata\UserBundle\Entity\User $idusuariomod = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuariomod', array($idusuariomod));

        return parent::setIdusuariomod($idusuariomod);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuariomod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuariomod', array());

        return parent::getIdusuariomod();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAreaModEstab(\Minsal\SiapsBundle\Entity\MntAreaModEstab $idAreaModEstab = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAreaModEstab', array($idAreaModEstab));

        return parent::setIdAreaModEstab($idAreaModEstab);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAreaModEstab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAreaModEstab', array());

        return parent::getIdAreaModEstab();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
