<?php

namespace Proxies\__CG__\Application\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FrmFormItem extends \Application\CoreBundle\Entity\FrmFormItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'id', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'nombreDescriptivo', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'tipoOrigen', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'mensajeAyuda', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'inscripcion', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'validacionEspecial', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'activo', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'fechaInicio', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'fechaFin', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'idTipoObjeto', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'ocultarOpciones', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'preSeleccionado', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'aplicarPluginMascara');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'id', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'nombreDescriptivo', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'tipoOrigen', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'mensajeAyuda', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'inscripcion', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'validacionEspecial', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'activo', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'fechaInicio', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'fechaFin', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'idTipoObjeto', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'ocultarOpciones', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'preSeleccionado', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormItem' . "\0" . 'aplicarPluginMascara');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FrmFormItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreDescriptivo($nombreDescriptivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreDescriptivo', array($nombreDescriptivo));

        return parent::setNombreDescriptivo($nombreDescriptivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreDescriptivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreDescriptivo', array());

        return parent::getNombreDescriptivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoOrigen($tipoOrigen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoOrigen', array($tipoOrigen));

        return parent::setTipoOrigen($tipoOrigen);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoOrigen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoOrigen', array());

        return parent::getTipoOrigen();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensajeAyuda($mensajeAyuda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensajeAyuda', array($mensajeAyuda));

        return parent::setMensajeAyuda($mensajeAyuda);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensajeAyuda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensajeAyuda', array());

        return parent::getMensajeAyuda();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscripcion($inscripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscripcion', array($inscripcion));

        return parent::setInscripcion($inscripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscripcion', array());

        return parent::getInscripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidacionEspecial($validacionEspecial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidacionEspecial', array($validacionEspecial));

        return parent::setValidacionEspecial($validacionEspecial);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidacionEspecial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidacionEspecial', array());

        return parent::getValidacionEspecial();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', array($fechaInicio));

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', array());

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFin($fechaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFin', array($fechaFin));

        return parent::setFechaFin($fechaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFin', array());

        return parent::getFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipoObjeto(\Application\CoreBundle\Entity\CtlTipoObjeto $idTipoObjeto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipoObjeto', array($idTipoObjeto));

        return parent::setIdTipoObjeto($idTipoObjeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipoObjeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipoObjeto', array());

        return parent::getIdTipoObjeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setOcultarOpciones($ocultarOpciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOcultarOpciones', array($ocultarOpciones));

        return parent::setOcultarOpciones($ocultarOpciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getOcultarOpciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOcultarOpciones', array());

        return parent::getOcultarOpciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreSeleccionado($preSeleccionado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreSeleccionado', array($preSeleccionado));

        return parent::setPreSeleccionado($preSeleccionado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreSeleccionado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreSeleccionado', array());

        return parent::getPreSeleccionado();
    }

    /**
     * {@inheritDoc}
     */
    public function setAplicarPluginMascara($aplicarPluginMascara)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAplicarPluginMascara', array($aplicarPluginMascara));

        return parent::setAplicarPluginMascara($aplicarPluginMascara);
    }

    /**
     * {@inheritDoc}
     */
    public function getAplicarPluginMascara()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAplicarPluginMascara', array());

        return parent::getAplicarPluginMascara();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoOrigenExtend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoOrigenExtend', array());

        return parent::getTipoOrigenExtend();
    }

}
