<?php

namespace Proxies\__CG__\Application\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FrmFormulario extends \Application\CoreBundle\Entity\FrmFormulario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'id', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'nombre', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'codigo', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'descripcion', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'activo', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'fechaInicio', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'fechaFin', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'publicado', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'fechaPublicacion', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'configGuardado', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'vistaEdit', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'vistaShow', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'vistaToPrint', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'idTipoFormulario');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'id', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'nombre', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'codigo', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'descripcion', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'activo', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'fechaInicio', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'fechaFin', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'publicado', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'fechaPublicacion', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'configGuardado', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'vistaEdit', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'vistaShow', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'vistaToPrint', '' . "\0" . 'Application\\CoreBundle\\Entity\\FrmFormulario' . "\0" . 'idTipoFormulario');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FrmFormulario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', array($codigo));

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', array());

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', array($fechaInicio));

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', array());

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFin($fechaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFin', array($fechaFin));

        return parent::setFechaFin($fechaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFin', array());

        return parent::getFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicado($publicado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicado', array($publicado));

        return parent::setPublicado($publicado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicado', array());

        return parent::getPublicado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPublicacion($fechaPublicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPublicacion', array($fechaPublicacion));

        return parent::setFechaPublicacion($fechaPublicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPublicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPublicacion', array());

        return parent::getFechaPublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfigGuardado($configGuardado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfigGuardado', array($configGuardado));

        return parent::setConfigGuardado($configGuardado);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfigGuardado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfigGuardado', array());

        return parent::getConfigGuardado();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setVistaEdit($vistaEdit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVistaEdit', array($vistaEdit));

        return parent::setVistaEdit($vistaEdit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVistaEdit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVistaEdit', array());

        return parent::getVistaEdit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVistaShow($vistaShow)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVistaShow', array($vistaShow));

        return parent::setVistaShow($vistaShow);
    }

    /**
     * {@inheritDoc}
     */
    public function getVistaShow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVistaShow', array());

        return parent::getVistaShow();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipoFormulario(\Application\CoreBundle\Entity\FrmTipoFormulario $idTipoFormulario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipoFormulario', array($idTipoFormulario));

        return parent::setIdTipoFormulario($idTipoFormulario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipoFormulario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipoFormulario', array());

        return parent::getIdTipoFormulario();
    }

    /**
     * {@inheritDoc}
     */
    public function setVistaToPrint($vistaToPrint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVistaToPrint', array($vistaToPrint));

        return parent::setVistaToPrint($vistaToPrint);
    }

    /**
     * {@inheritDoc}
     */
    public function getVistaToPrint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVistaToPrint', array());

        return parent::getVistaToPrint();
    }

}
