<?php

namespace Proxies\__CG__\Minsal\SiapsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MntAtenAreaModEstab extends \Minsal\SiapsBundle\Entity\MntAtenAreaModEstab implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'idAreaModEstab', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'idAtencion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'nombreAmbiente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'idAmbienteIndependiente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'condicion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'habilitadoFarmaciaEspecializada');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'idAreaModEstab', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'idAtencion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'nombreAmbiente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'idAmbienteIndependiente', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'condicion', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntAtenAreaModEstab' . "\0" . 'habilitadoFarmaciaEspecializada');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MntAtenAreaModEstab $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAreaModEstab(\Minsal\SiapsBundle\Entity\MntAreaModEstab $idAreaModEstab = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAreaModEstab', array($idAreaModEstab));

        return parent::setIdAreaModEstab($idAreaModEstab);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAreaModEstab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAreaModEstab', array());

        return parent::getIdAreaModEstab();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAtencion(\Minsal\SiapsBundle\Entity\CtlAtencion $idAtencion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAtencion', array($idAtencion));

        return parent::setIdAtencion($idAtencion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAtencion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAtencion', array());

        return parent::getIdAtencion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimiento(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimiento', array($idEstablecimiento));

        return parent::setIdEstablecimiento($idEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimiento', array());

        return parent::getIdEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreAmbiente($nombreAmbiente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreAmbiente', array($nombreAmbiente));

        return parent::setNombreAmbiente($nombreAmbiente);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreAmbiente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreAmbiente', array());

        return parent::getNombreAmbiente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondicion($condicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondicion', array($condicion));

        return parent::setCondicion($condicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondicion', array());

        return parent::getCondicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAmbienteIndependiente(\Minsal\SiapsBundle\Entity\MntAmbienteIndependiente $idAmbienteIndependiente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAmbienteIndependiente', array($idAmbienteIndependiente));

        return parent::setIdAmbienteIndependiente($idAmbienteIndependiente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAmbienteIndependiente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAmbienteIndependiente', array());

        return parent::getIdAmbienteIndependiente();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaEspecializada($habilitadoFarmaciaEspecializada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaEspecializada', array($habilitadoFarmaciaEspecializada));

        return parent::setAreaEspecializada($habilitadoFarmaciaEspecializada);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabilitadoFarmaciaEspecializada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabilitadoFarmaciaEspecializada', array());

        return parent::getHabilitadoFarmaciaEspecializada();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreConsulta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreConsulta', array());

        return parent::getNombreConsulta();
    }

}
