imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.xml }
    - { resource: bundles/endroid_qr.yml }
    - { resource: bundles/sonata_admin.yml }
    - { resource: bundles/sonata_block.yml }
    - { resource: bundles/sonata_cache.yml }
    - { resource: bundles/sonata_core.yml }
    - { resource: bundles/sonata_formatter.yml }
    - { resource: bundles/sonata_user.yml }
    - { resource: bundles/fos_user.yml }
    - { resource: @MinsalFarmaciaBundle/Resources/config/services.yml }
    - { resource: @MinsalSiapsBundle/Resources/config/services.yml }
    - { resource: @MinsalSeguimientoBundle/Resources/config/services.yml }
    - { resource: bundles/sonata_doctrine_orm_admin.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        cookie_lifetime: 0
        handler_id:  ~
        gc_probability:  0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'ApplicationCoreBundle:CRUD:FieldType/edit_field_file.html.twig'

    globals:
        signed_modules: %signed_modules%
        max_iddle_time: %session_max_idle_time%
        print_ticket:   %print_ticket%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        default_entity_manager: default
        dql:
            numeric_functions:
                TO_NUMBER:  Application\CoreBundle\Dql\ToNumberDql
            string_functions:
                COALESCE:   Application\CoreBundle\Dql\CoalesceDql
                NULLIF:     Application\CoreBundle\Dql\NullIfDql
                CONCAT_WS:  Application\CoreBundle\Dql\ConcatWsDql
                UNACCENT:   Application\CoreBundle\Dql\UnaccentString
                INITCAP:    Application\CoreBundle\Dql\InitcapDql
            datetime_functions:
                DATE:       Application\CoreBundle\Dql\DateDql

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Knp MenuBundle
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

#Servicios
services:
    request_listener.service:
        class: Application\CoreBundle\EventListener\RequestListener
        arguments: ["@security.context", "@router", "@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRouteRequest }

    session_idle.service:
        class: Application\CoreBundle\EventListener\SessionOutListener
        arguments: ["@session", "@security.context", "@router", %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    calendar.load_events:
        class:  Minsal\SiapsBundle\EventListener\CalendarEventListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }

    jasper.build.reports:
        class: Minsal\SiapsBundle\Service\JasperReportService\JasperReportService
        arguments: [%jasper_username%, %jasper_password%, %jasper_url%]

    core_user_manager:
        class:  Application\CoreBundle\Security\User\UserProvider
        arguments: ["@fos_user.user_manager", "@service_container", "@doctrine.orm.entity_manager"]

    core.security.authentication.provider:
        class:  Application\CoreBundle\Security\Authentication\Provider\AuthenticationProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces", "@service_container", 'rsa', "@security.user_checker", "@security.encoder_factory"]

    core.security.authentication.listener:
        class:  Application\CoreBundle\Security\Firewall\ListenerInterface
        arguments: ["@security.context", "@security.authentication.manager", 'rsa',"@security.http_utils", "@security.authentication.session_strategy", "@event_dispatcher", "@logger", "@http_kernel", "@service_container"]

    core.authentication.handler:
        class:  Application\CoreBundle\Security\Authentication\Handler\AuthenticationHandler
        arguments: ["@http_kernel", "@security.http_utils", "@logger", "@service_container"]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    form.generator.service:
        class:  Application\CoreBundle\Service\FormGeneratorService
        scope: prototype
        arguments: [@service_container]

    form.type_extension.help_message:
        class: Application\CoreBundle\Form\Extension\HelpMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: form }

    lab_examnresult:
        class: Minsal\LaboratorioBundle\Service\ExamnResultService
        arguments: ["@service_container"]
    
    hl7.service:
        class: Minsal\LaboratorioBundle\Service\Hl7Service
        arguments: ["@service_container"]

    cit_citas_dia.services:
        class: Minsal\CitasBundle\Service\CitasService
        arguments: ["@service_container"]

    cit_citas_procedimientos.services:
        class: Minsal\CitasBundle\Service\CitasProcedimientosService
        arguments: ["@service_container"]

    mnt_expediente.services:
        class: Minsal\SiapsBundle\Service\ExpedienteService
        arguments: ["@service_container"]

    application_core_bundle.file_type_extension:
        class: Application\CoreBundle\Form\Extension\FileTypeExtension
        tags:
            - { name: form.type_extension, alias: file }

sonata_doctrine_orm_admin:
    templates:
        types:
            show:
                html:    MinsalSiapsBundle:CRUD:Type/show_field_html.html.twig
