

_inicio:
    pattern:  /
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path:  /admin/login
        permanent: true

#BLOQUE MINSAL BUNDLES
minsal_siaps:
    resource: "@MinsalSiapsBundle/Controller/"
    type:     annotation
    prefix:   /

minsal_farmacia:
    resource: "@MinsalFarmaciaBundle/Controller/"
    type:     annotation
    prefix:   /


minsal_seguimiento:
    resource: "@MinsalSeguimientoBundle/Controller/"
    type:     annotation
    prefix:   /

minsal_citas:
    resource: "@MinsalCitasBundle/Controller/"
    type:     annotation
    prefix:   /

minsal_laboratorio:
    resource: "@MinsalLaboratorioBundle/Controller/"
    type:     annotation
    prefix:   /

application_core:
    resource: "@ApplicationCoreBundle/Controller/"
    type:     annotation
    prefix:   /

application_soap:
    resource: "@ApplicationSoapBundle/Controller/"
    type:     annotation
    prefix:   /

application_soap_routing:
    resource: '@ApplicationSoapBundle/Resources/config/routing.yml'
    prefix: /

application_api:
    resource: "@ApplicationApiBundle/Controller/"
    type:     annotation
    prefix:   /api

# Sonata AdminBundle
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Sonata CacheBundle
sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

# Sonata UserBundle
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#Form Generation Test
generate_formtest:
    path: /generateformtest/{id}
    defaults: { _controller: MinsalSeguimientoBundle:FormGeneratorTest:generateFormTest }

#web service
mespecialidades:
    path:      /espe/{establecimiento}/{host}/{method}
    defaults:  { _controller: MinsalSeguimientoBundle:Cliente:obtenerEspecialidades }

mespecialidad:
    path:      /espe/{establecimiento}/{host}/{especialidad}
    defaults:  { _controller: MinsalSeguimientoBundle:Cliente:obtenerEspecialidades }



referencia:
    path:      /referencia/guardar/{establecimiento}/{host}
    defaults:  { _controller: MinsalSeguimientoBundle:Cliente:guardarReferencia }

#QR
EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode
