jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN,ROLE_USER_LISTAREXPEDIENTES,ROLE_USER_BUSCAREMERGENCIA,ROLE_USER_CONSULTAR,ROLE_USER_DEPURACION]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented
        ROLE_SONATA_LAB_SEC_SOLICITUDESTUDIOS:
            - ROLE_MINSAL_LABORATORIO_ADMIN_SEC_SOLICITUDESTUDIOS_ASSIGNEXAM
            - ROLE_MINSAL_LABORATORIO_ADMIN_SEC_SOLICITUDESTUDIOS_HISTORY
        ROLE_SONATA_FARM_RECETAS:
            - ROLE_MINSAL_FARMACIA_ADMIN_FARM_RECETAS_ASSIGNRECETA
            - ROLE_SONATA_ADMIN_FARMRECETAS_COMPLEMENT
            - ROLE_SONATA_ADMIN_FARMRECETAS_COMPLEMENTALL
        ROLE_SONATA_CIT_CITAS_DIA:
            - ROLE_SONATA_ADMIN_CITCITASDIA_TRANSFER
            - ROLE_SONATA_ADMIN_CITAMEDICAS
            - ROLE_SONATA_ADMIN_CITCITASDIA_CITAINTEGRAL
            - ROLE_SONATA_ADMIN_CITCITASDIA_ASIGNAR
            - ROLE_SONATA_ADMIN_CITCITASDIA_LISTAMEDICA_LIST
            - ROLE_SONATA_ADMIN_CITCITASDIA_REFERENCIA
            - ROLE_SONATA_ADMIN_CITCITASDIA_REPROGRAMAR
            - ROLE_SONATA_ADMIN_AGENDAMEDICA_EMPLEADO_ESPECIALIDAD_LIST
            - ROLE_SONATA_ADMIN_CITCITASDIA_EXCLUYENDO_TIPO_CITA
            - ROLE_SONATA_ADMIN_CITCITASDIA_MEDICO_EXCLUYENDO_TIPO_CITA
            - ROLE_SONATA_ADMIN_CITCITASDIA_REPORTES
            - ROLE_SONATA_ADMIN_AGENDADIA
        ROLE_SONATA_CIT_CITAS_PROCEDIMIENTOS:
            - ROLE_SONATA_ADMIN_CITCITASPROCEDIMIENTOS_REFERENCIA
            - ROLE_MINSAL_CITAS_ADMIN_CIT_CITAS_PROCEDIMIENTOS_AGENDA
            - ROLE_MINSAL_CITAS_ADMIN_CIT_CITAS_PROCEDIMIENTOS_PROCEDIMIENTOEMPLEADO_LIST
            - ROLE_MINSAL_CITAS_ADMIN_CIT_CITAS_PROCEDIMIENTOS_REPORTES
        ROLE_SONATA_SECHISTORIALCLINICO:
            - ROLE_SONATA_ADMIN_SECHISTORIALCLINICO_RETROACTIVE
            - ROLE_SONATA_ADMIN_SECHISTORIALCLINICO_PACIENTESAPTOSESPECIALIZADA
            - ROLE_SONATA_ADMIN_CONSULTAS_ATENDIDAS
        ROLE_SONATA_CLINICASELECCION:
            - ROLE_SONATA_ADMIN_CITCITASDIA_CSELECCION
        ROLE_API_LABORATORIO:
            - ROLE_API_CHECKOUT
            - ROLE_API_LABORATORIO_INGRESORESULTADOS
            - ROLE_API_LABORATORIO_ENVIAR_SOLICITUD_EQUIPOAUTOMATIZADO
    providers:
        fos_userbundle:
            id: core_user_manager
            #id: fos_user.user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        api:
            #switch_user:        false
            pattern:            ^/api
            context:            api
            logout:
                invalidate_session: true
            anonymous:          true

        admin:
            pattern:            .*
            context:            user
            rsa:                true
            switch_user:        true
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                use_referer:    true
                default_target_path:  /admin/dashboard
            logout:
                path:           /admin/logout
                target:         /admin/login
                invalidate_session: true
            anonymous:          true
        # -> end custom configuration

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/load/digitalSignature$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/soap, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/espe, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/siaps/timeInfo$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/checkin$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin, role: [ROLE_USER, ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/admin/dashboard, role: [ROLE_USER, ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: ROLE_USER }
