<?php

namespace Application\SoapBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class InterfaceLisController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Application\SoapBundle\Controller\InterfaceLisController();
        return $instance;
    }
}
