<?php

namespace Application\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MntUserTourController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Application\CoreBundle\Controller\MntUserTourController();
        return $instance;
    }
}
