<?php

namespace Application\ApiBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ApiController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Application\ApiBundle\Controller\ApiController();
        return $instance;
    }
}
