<?php

namespace Endroid\Bundle\QrCodeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class QrCodeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Endroid\Bundle\QrCodeBundle\Controller\QrCodeController();
        return $instance;
    }
}
