<?php

namespace Minsal\CitasBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CitDistribucionProcedimientoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Minsal\CitasBundle\Controller\CitDistribucionProcedimientoController();
        return $instance;
    }
}
