<?php

namespace Minsal\SeguimientoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TarSecTarAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Minsal\SeguimientoBundle\Controller\TarSecTarAdminController();
        return $instance;
    }
}
