<?php

namespace Minsal\FarmaciaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FarmRecetasAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Minsal\FarmaciaBundle\Controller\FarmRecetasAdminController();
        return $instance;
    }
}
