<?php

namespace Minsal\SiapsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MntExpedienteAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Minsal\SiapsBundle\Controller\MntExpedienteAdminController();
        return $instance;
    }
}
