<?php

namespace Minsal\LaboratorioBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SecSolicitudestudiosController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Minsal\LaboratorioBundle\Controller\SecSolicitudestudiosController();
        return $instance;
    }
}
