<?php

namespace Minsal\LaboratorioBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * LabConfExamenEstabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabConfExamenEstabRepository extends EntityRepository {

    public function getStandardExamByProgram($idAtencion) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $query = $qb->select("DISTINCT t04")
        ->from('MinsalLaboratorioBundle:LabConfExamenEstab', 't01')
        ->innerJoin('t01.idformulario', 't02', 'WITH', 't02.idAtencion = :idAtencion')
        ->innerJoin('t01.idexamen', 't03')
        ->innerJoin('t03.idExamenServicioDiagnostico', 't04')
        ->where("t01.condicion = :condicion")
        ->andWhere("t02.condicion = :condicion")
        ->andWhere("t03.activo = :activo")
        ->andWhere('t04.activo = :activo')
        ->setParameters(array(':idAtencion' => $idAtencion, ':condicion' => 'H', ':activo' => true))
        ->getQuery();

        $result = $query->getArrayResult();
        return $result;
    }
}
